# Generated by Django 5.2.14 on 2026-05-29 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(default="WaferClassifier", max_length=100),
                ),
                ("version", models.CharField(max_length=30)),
                ("f1_score", models.DecimalField(decimal_places=4, max_digits=5)),
                ("registered_at", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-registered_at"],
            },
        ),
        migrations.CreateModel(
            name="WaferLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "sample_image",
                    models.ImageField(blank=True, null=True, upload_to="wafer/labels/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WaferAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("analysis_code", models.CharField(max_length=50, unique=True)),
                ("uploaded_file", models.FileField(upload_to="wafer/uploads/")),
                (
                    "wafer_image",
                    models.ImageField(blank=True, null=True, upload_to="wafer/images/"),
                ),
                (
                    "yield_threshold",
                    models.DecimalField(decimal_places=2, default=90, max_digits=5),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("done", "완료"),
                            ("failed", "실패"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("predicted_label", models.CharField(blank=True, max_length=50)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                (
                    "result_csv",
                    models.FileField(blank=True, null=True, upload_to="wafer/results/"),
                ),
                (
                    "model_version",
                    models.CharField(default="resnet34-v1", max_length=50),
                ),
                ("summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wafer_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcessRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.PositiveSmallIntegerField()),
                ("process", models.CharField(max_length=50)),
                ("score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("reason", models.TextField()),
                ("stop_alert", models.BooleanField(default=False)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="analyses.waferanalysis",
                    ),
                ),
            ],
            options={
                "ordering": ["rank"],
                "unique_together": {("analysis", "rank")},
            },
        ),
    ]
