# Generated by Django 5.2.14 on 2026-05-29 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lot_id", models.CharField(max_length=80, unique=True)),
                ("product_code", models.CharField(blank=True, max_length=80)),
                ("process", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ready", "대기"),
                            ("running", "진행"),
                            ("hold", "보류"),
                            ("done", "완료"),
                        ],
                        default="ready",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["lot_id"],
            },
        ),
        migrations.AddField(
            model_name="waferanalysis",
            name="die_size",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="waferanalysis",
            name="equipment_id",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="waferanalysis",
            name="inspection_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="waferanalysis",
            name="process",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="waferanalysis",
            name="recipe_id",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="waferanalysis",
            name="step",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="waferanalysis",
            name="wafer_id",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="waferanalysis",
            name="wafer_index",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="waferanalysis",
            name="wafer_map_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="waferanalysis",
            name="yield_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.CreateModel(
            name="AnalysisBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_code", models.CharField(max_length=50, unique=True)),
                ("uploaded_file", models.FileField(upload_to="wafer/batches/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("done", "완료"),
                            ("failed", "실패"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("total_wafers", models.PositiveIntegerField(default=0)),
                ("failed_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analysis_batches",
                        to="analyses.lot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="waferanalysis",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wafer_analyses",
                to="analyses.analysisbatch",
            ),
        ),
        migrations.AddField(
            model_name="waferanalysis",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="wafer_analyses",
                to="analyses.lot",
            ),
        ),
        migrations.CreateModel(
            name="LotAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("owner", "담당자"), ("reviewer", "검토자")],
                        default="owner",
                        max_length=20,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="analyses.lot",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lot_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["lot__lot_id", "user__username"],
                "unique_together": {("lot", "user")},
            },
        ),
    ]
