# Generated by Django 5.2.15 on 2026-06-25 01:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0010_line_lineassignment_lot_line"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisbatch",
            name="favorited_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorite_analysis_batches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customanalysis",
            name="favorited_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorite_custom_analyses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
